name: Network Discovery

on:
  workflow_dispatch:
    inputs:
      seed_devices:
        description: 'Comma-separated list of seed devices (IP:PORT)'
        required: true
        default: '192.168.1.1,10.0.0.1:22,172.16.1.1:4446'
      username:
        description: 'Primary username for device authentication'
        required: true
        default: 'admin'
      use_multiple_credentials:
        description: 'Use multiple credential sets'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      additional_usernames:
        description: 'Additional usernames (comma-separated, if multiple credentials enabled)'
        required: false
        default: 'cisco,operator'
      discovery_method:
        description: 'Discovery method to use'
        required: true
        default: 'neighbor_discovery'
        type: choice
        options:
          - neighbor_discovery
          - subnet_scan
      max_depth:
        description: 'Maximum discovery depth'
        required: false
        default: '3'
      timeout:
        description: 'Connection timeout in seconds'
        required: false
        default: '60'
      max_wait_time:
        description: 'Maximum time to wait for discovery completion (seconds)'
        required: false
        default: '1800'
      poll_interval:
        description: 'Status check interval (seconds)'
        required: false
        default: '10'

jobs:
  run-discovery:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Pull the discovery service container
      - name: Pull discovery service container
        run: |
          docker pull ghcr.io/presidio-federal/hai-discovery-tools/discovery-service:latest
      
      # Start the discovery service
      - name: Start discovery service
        run: |
          docker run -d --name discovery-service -p 8080:8080 ghcr.io/presidio-federal/hai-discovery-tools/discovery-service:latest
          # Wait for service to start
          sleep 5
      
      # Run discovery
      - name: Run discovery
        id: discovery
        run: |
          # Convert comma-separated list to JSON array
          SEED_DEVICES=$(echo "${{ github.event.inputs.seed_devices }}" | sed 's/,/","/g' | sed 's/^/["/g' | sed 's/$/"]/')
          
          # Prepare credentials
          if [ "${{ github.event.inputs.use_multiple_credentials }}" == "true" ]; then
            # Start with primary username
            USERNAMES=("${{ github.event.inputs.username }}")
            
            # Add additional usernames if provided
            if [ -n "${{ github.event.inputs.additional_usernames }}" ]; then
              IFS=',' read -r -a ADDITIONAL_USERNAMES <<< "${{ github.event.inputs.additional_usernames }}"
              USERNAMES+=("${ADDITIONAL_USERNAMES[@]}")
            fi
            
            # Get passwords from GitHub secrets
            # Format: DEVICE_PASSWORD for primary, ALT_DEVICE_PASSWORD_1, ALT_DEVICE_PASSWORD_2, etc. for additional
            PASSWORDS=("${{ secrets.DEVICE_PASSWORD }}")
            
            for i in "${!ADDITIONAL_USERNAMES[@]}"; do
              secret_name="ALT_DEVICE_PASSWORD_$((i+1))"
              # Try to dynamically access the secret
              password_var="secrets.${secret_name}"
              password="${!password_var}"
              if [ -n "$password" ]; then
                PASSWORDS+=("$password")
              else
                # Fallback to a generic alt password secret if specific one not found
                PASSWORDS+=("${{ secrets.ALT_DEVICE_PASSWORD }}")
              fi
            done
            
            # Build credentials JSON array
            CREDENTIALS="["
            for i in "${!USERNAMES[@]}"; do
              if [ $i -gt 0 ]; then
                CREDENTIALS="${CREDENTIALS},"
              fi
              CREDENTIALS="${CREDENTIALS}{\"username\": \"${USERNAMES[$i]}\", \"password\": \"${PASSWORDS[$i]}\"}"
            done
            CREDENTIALS="${CREDENTIALS}]"
            
            echo "Using ${#USERNAMES[@]} credential sets"
          else
            # Just use the primary username/password
            CREDENTIALS="[{\"username\": \"${{ github.event.inputs.username }}\", \"password\": \"${{ secrets.DEVICE_PASSWORD }}\"}]"
            echo "Using single credential set"
          fi
          
          # Start discovery - IMPORTANT: We're NOT using wait_for_results=true here
          # because we want to handle the waiting with proper polling
          RESPONSE=$(curl -s -X POST "http://localhost:8080/discover" \
            -H "Content-Type: application/json" \
            -d "{
              \"seed_devices\": $SEED_DEVICES,
              \"credentials\": $CREDENTIALS,
              \"method\": \"${{ github.event.inputs.discovery_method }}\",
              \"max_depth\": ${{ github.event.inputs.max_depth }},
              \"timeout\": ${{ github.event.inputs.timeout }}
            }")
          
          # Extract job ID
          JOB_ID=$(echo $RESPONSE | jq -r '.job_id')
          if [ -z "$JOB_ID" ] || [ "$JOB_ID" == "null" ]; then
            echo "Failed to get job ID from response:"
            echo $RESPONSE
            exit 1
          fi
          
          echo "Job ID: $JOB_ID"
          echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT
          
          # Create export directory
          mkdir -p discovery_exports
          
          # Wait for discovery to complete with timeout
          echo "Waiting for discovery job to complete..."
          MAX_WAIT_TIME=${{ github.event.inputs.max_wait_time || 1800 }}  # Default: 30 minutes
          WAIT_INTERVAL=${{ github.event.inputs.poll_interval || 10 }}    # Default: 10 seconds
          ELAPSED_TIME=0
          
          while [ $ELAPSED_TIME -lt $MAX_WAIT_TIME ]; do
            # Get job status
            STATUS_RESPONSE=$(curl -s "http://localhost:8080/discover/$JOB_ID")
            JOB_STATUS=$(echo $STATUS_RESPONSE | jq -r '.status')
            
            echo "Current status: $JOB_STATUS (waited ${ELAPSED_TIME}s)"
            
            # Check if job is complete
            if [ "$JOB_STATUS" == "completed" ] || [ "$JOB_STATUS" == "failed" ]; then
              break
            fi
            
            # Wait before checking again
            sleep $WAIT_INTERVAL
            ELAPSED_TIME=$((ELAPSED_TIME + WAIT_INTERVAL))
          done
          
          if [ $ELAPSED_TIME -ge $MAX_WAIT_TIME ]; then
            echo "Warning: Discovery job timed out after ${MAX_WAIT_TIME}s. Continuing with available data."
          else
            echo "Discovery job completed in ${ELAPSED_TIME}s."
          fi
          
          # Get summary information
          SUMMARY=$(echo $STATUS_RESPONSE | jq -r '.summary // empty')
          if [ -n "$SUMMARY" ]; then
            echo "Discovery summary:"
            echo $SUMMARY | jq
          fi
      
      # Export discovery data
      - name: Export discovery data
        run: |
          JOB_ID="${{ steps.discovery.outputs.job_id }}"
          echo "Exporting data for job $JOB_ID..."
          
          # Export as JSON
          echo "Exporting JSON data..."
          curl -s "http://localhost:8080/discover/$JOB_ID/export?format=json" > discovery_exports/discovery_data.json
          
          # Check if we got valid JSON
          if ! jq empty discovery_exports/discovery_data.json 2>/dev/null; then
            echo "Warning: Invalid or empty JSON data received"
            cat discovery_exports/discovery_data.json
          else
            echo "JSON data exported successfully"
            # Show device count
            echo "Discovered devices: $(jq '.devices | length' discovery_exports/discovery_data.json)"
          fi
          
          # Export device inventory
          echo "Exporting device inventory..."
          curl -s "http://localhost:8080/discover/$JOB_ID/export/device_inventory" > discovery_exports/device_inventory.csv
          
          # Export interface inventory
          echo "Exporting interface inventory..."
          curl -s "http://localhost:8080/discover/$JOB_ID/export/interface_inventory" > discovery_exports/interface_inventory.csv
          
          # Export topology visualization
          echo "Exporting topology visualization..."
          curl -s "http://localhost:8080/discover/$JOB_ID/topology" > discovery_exports/topology.html
      
      # Upload artifacts
      - name: Upload discovery results
        uses: actions/upload-artifact@v4
        with:
          name: discovery-results
          path: discovery_exports/
          retention-days: 7
